### ISSUE TITLE
Papers and videos in the research page are not adjusting properly when the window is resized.

### ISSUE THREAD

**Issue by ceilican** [StabilityNexus/Website#3]
Papers and videos are becoming stretched when the research page is resized.

<img width="707" alt="Screenshot 2024-12-02 at 11 21 25" src="https://github.com/user-attachments/assets/22187adb-39f5-45f7-abfe-7871b5ca145e">

**Comment by Arnav-Nehra** [comment]
@ceilican please assign me

**Comment by ceilican** [comment]
@SHOBHIT112005, will you take this issue?

**Comment by SHOBHIT112005** [comment]
Thnx for the opportunity Bruno, I can't clone this repo, I have been
trying, having issues

**Comment by ceilican** [comment]
What kind of issues, @SHOBHIT112005 ?

**Comment by SHOBHIT112005** [comment]
![image](https://github.com/user-attachments/assets/1be04aa4-95bf-43f8-847e-1ed4551305c7)
like this

**Comment by SHOBHIT112005** [comment]
I guess my internet is not good.

**Comment by SHOBHIT112005** [comment]
Yes
